### ISSUE TITLE
Deduplicate Licenses

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#146] opened 2020-07-14 15:35 UTC
I assume we want to display the correct license in a clear format.

I suggest to improve in this regard:

- Match licenses to [SPDX](https://spdx.org/licenses/)
- Use SPDX Full name in list
- Link to SPDX license page like https://spdx.org/licenses/BSD-3-Clause.html
- When the license can not clearly get matched (like GPL or BSD), display as error in reporitory
- When a repo uses a different license than the most popular, show a warning

**Comment by AMDmi3** [comment] 2020-07-14 17:37
Duplicate of repology/repology-updater#225. Patches welcome.

**Closed by AMDmi3** 2020-07-14 17:37 UTC
