### ISSUE TITLE
Add stats about average package update time

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#87] opened 2019-11-02 22:04 UTC
It would be interesting to see which distribution is the fastest in updating packages.

For that, we would need the average time a distribution takes to update a package.

We don't have the time when a new release is actually made, but when one repository updates the package. We have the time for other repositories in relation to that.

`Newest version updated to 0.5.2 by AUR, in 5 days since the last update`
`nixpkgs unstable has caught up with the newest version in a day`

Source: https://repology.org/project/reuse/history

So for the package _reuse_ AUR would get the update time 0 and nixpkgs unstable 1. Then we calculate the average for all packages and sort the table after lowest value.

When a distribution don't has the latest version, we might reuse the time for the previous package update? Or just exclude that package and only calculate the data for up-to-date packages? Then distros with few up-to-date packages would have an unfair advantage if they update them quickly?
packages up to date is a different statistic...

**Comment by AMDmi3** [comment] 2019-11-02 22:40
This is wrong repository for this issue. Duplicate of repology/repology-updater#62.

**Closed** 2019-11-02 22:40 UTC
