### ISSUE TITLE
CVE shows affected version multiple times

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#136] opened 2020-06-11 07:49 UTC
![Screenshot from 2020-06-11 09-43-33](https://user-images.githubusercontent.com/91113/84359030-4d7bf680-abc8-11ea-8f1e-126cacf7589d.png)

because the patch part is cut off

![Screenshot from 2020-06-11 09-43-41](https://user-images.githubusercontent.com/91113/84359042-510f7d80-abc8-11ea-869c-290c29393dab.png)

so to fix it, include patch part in version or remove duplicates

**Comment by AMDmi3** [comment] 2020-06-11 14:52
Regarding ignored CPE _update_ field (one which contains `patch*` here), this issue is duplicate of repology/repology-updater#1043. Regarding the duplication of versions, there's no need to counter it specifically as it should be gone after the mentioned issue is resolved. Otherwise, it would indicate some problem in data or code.

**Closed by AMDmi3** 2020-06-11 14:52 UTC
